### ISSUE TITLE
Make camelize of variable names optional

### ISSUE THREAD

**Issue by phillipoertel** [Coffa/client_variable#1]
Hi,

we are just migrating from our own solution to client_variable. Since client_variable automagically camelizes all variable names, we have to be very careful not to introduce subtle bugs. Hoever, I understand this behaviour may be desirable for people who start with client_variable from scratch.

Would it be possible to make that behaviour optional and configurable? Right now I would have to patch 2 methods in https://github.com/Coffa/client_variable/blob/master/lib/client_variable/helper/view.rb, which isn't ideal.

Kind regards,
Phillip

**Comment by MQuy** [comment]
i think you're right, we should have configuration about that. Ok, I'll add that one for define how it works and will let you know when it'll be finished :+1:

**Comment by phillipoertel** [comment]
Thank you very much!
